site_name: Django Post Later Documentation
copyright: Copyright &copy; 2022 Daniel Andrlik
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Models: models.md
  - Views: views.md
  - Exceptions: exceptions.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Security: security.md
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: deep-purple
repo_url: https://github.com/andrlik/django-post-later/
plugins:
  - search
  - autorefs
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import django"
            - "django.setup()"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
