# Generated by Django 4.1.3 on 2022-11-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0003_alter_mastodonavatar_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastodoninstanceclient",
            name="client_id",
            field=models.CharField(
                blank=True,
                help_text="Unique client id for instance.",
                max_length=100,
                null=True,
                verbose_name="Client Id",
            ),
        ),
        migrations.AlterField(
            model_name="mastodoninstanceclient",
            name="client_secret",
            field=models.CharField(
                blank=True,
                help_text="Client secret token for instance.",
                max_length=100,
                null=True,
                verbose_name="Client Secret",
            ),
        ),
    ]
