# Generated by Django 4.1.3 on 2022-11-21 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import post_later.models.statuses
import post_later.validators
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post_later", "0005_alter_mastodonuserauth_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user object that owns this instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VideoMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="Type of media being uploaded. Will attempt to guess from file extension.",
                        max_length=20,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Description for visually impaired.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "focus_x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[post_later.validators.validate_focal_field_limit],
                    ),
                ),
                (
                    "focus_y",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[post_later.validators.validate_focal_field_limit],
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="Media being uploaded.",
                        upload_to=post_later.models.statuses.media_directory_path,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Calculated duration of video.", null=True
                    ),
                ),
                (
                    "media_group",
                    models.ForeignKey(
                        help_text="Group of media that will be attached to a post.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_later.mediagroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user object that owns this instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ImageMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="Type of media being uploaded. Will attempt to guess from file extension.",
                        max_length=20,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Description for visually impaired.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "focus_x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[post_later.validators.validate_focal_field_limit],
                    ),
                ),
                (
                    "focus_y",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[post_later.validators.validate_focal_field_limit],
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        help_text="Image file being uploaded.",
                        upload_to=post_later.models.statuses.media_directory_path,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Generated thumbnail for images.",
                        null=True,
                        upload_to=post_later.models.statuses.media_thumbnail_directory_path,
                    ),
                ),
                (
                    "media_group",
                    models.ForeignKey(
                        help_text="Group of media that will be attached to a post.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_later.mediagroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user object that owns this instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
