# Generated by Django 4.1.3 on 2022-12-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "post_later",
            "0007_account_accountstats_mediaattachment_scheduledpost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="auth_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="auth_object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("pending", "Created, but not authenticated yet."),
                    ("active", "Active account"),
                    ("trash", "Pending deletion..."),
                ],
                db_index=True,
                default="pending",
                help_text="Status of account.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("mast", "Mastodon"),
                    ("twitter", "Twitter"),
                    ("insta", "Instagram"),
                ],
                db_index=True,
                default="mast",
                help_text="What type of social account is this?",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["auth_content_type", "auth_object_id"],
                name="post_later__auth_co_b2eb86_idx",
            ),
        ),
    ]
