# Generated by Django 4.1.3 on 2022-12-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "post_later",
            "0008_account_auth_content_type_account_auth_object_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="account",
            name="post_later__auth_co_b2eb86_idx",
        ),
        migrations.RemoveField(
            model_name="account",
            name="auth_content_type",
        ),
        migrations.RemoveField(
            model_name="account",
            name="auth_object_id",
        ),
        migrations.AddField(
            model_name="mastodonuserauth",
            name="social_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mastodon_auth",
                to="post_later.account",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("mastodon", "Mastodon"),
                    ("twitter", "Twitter"),
                    ("instagram", "Instagram"),
                ],
                db_index=True,
                default="mastodon",
                help_text="What type of social account is this?",
                max_length=20,
            ),
        ),
    ]
