# Generated by Django 4.1.3 on 2022-12-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0009_remove_account_post_later__auth_co_b2eb86_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
    ]
