# Generated by Django 4.1.3 on 2022-12-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0010_remove_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastodonuserauth",
            name="social_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mastodon_auth",
                to="post_later.account",
            ),
        ),
    ]
