# Generated by Django 4.1.3 on 2022-12-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0012_mediaattachment_remote_id_scheduledpost_remote_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledpost",
            name="account",
            field=models.ForeignKey(
                help_text="Account where this post is scheduled to be sent.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_posts",
                to="post_later.account",
            ),
        ),
        migrations.AddField(
            model_name="scheduledthread",
            name="account",
            field=models.ForeignKey(
                help_text="Account where this thread is scheduled to be sent.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_threads",
                to="post_later.account",
            ),
        ),
    ]
