# Generated by Django 4.1.3 on 2022-12-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0014_alter_scheduledpost_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastodonuserauth",
            name="account_url",
            field=models.URLField(
                blank=True, help_text="URL of user profile on instance.", null=True
            ),
        ),
    ]
