# Generated by Django 4.1.3 on 2022-12-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0015_mastodonuserauth_account_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaattachment",
            name="video_duration",
        ),
        migrations.AddField(
            model_name="mediaattachment",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration of video or audio, if applicable.",
                null=True,
            ),
        ),
    ]
