# Generated by Django 4.1.3 on 2022-12-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0017_scheduledpost_queued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaattachment",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("error", "Error, awaiting retry"),
                    ("failed", "Failed to upload after multiple attempts."),
                    ("complete", "Uploaded successfully"),
                ],
                default="pending",
                help_text="Status of the remote upload to service.",
                max_length=15,
            ),
        ),
    ]
