# Generated by Django 4.1.3 on 2022-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0018_mediaattachment_upload_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaattachment",
            name="num_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of failures to upload this piece of media."
            ),
        ),
    ]
