# Generated by Django 4.1.3 on 2022-12-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0022_mediaattachment_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaattachment",
            name="account",
            field=models.ForeignKey(
                help_text="Social account this media is associated with.",
                on_delete=django.db.models.deletion.CASCADE,
                to="post_later.account",
            ),
        ),
    ]
