# Generated by Django 4.1.3 on 2023-01-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0023_alter_mediaattachment_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["account_type", "created"]},
        ),
        migrations.RemoveField(
            model_name="scheduledboost",
            name="boost_status",
        ),
        migrations.RemoveField(
            model_name="scheduledpost",
            name="post_status",
        ),
        migrations.AddField(
            model_name="scheduledboost",
            name="queued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If the remotes system supports queuing, what time did we successfully queue for?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledboost",
            name="remote_queue_id",
            field=models.CharField(
                blank=True,
                help_text="What remote id did the target server give to the queued object?",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledboost",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("error", "Error, awaiting retry."),
                    ("failed", "Failed to post after multiple retries. Giving up."),
                    ("queued", "Queued on remote server"),
                    ("complete", "Sucessfully posted."),
                ],
                db_index=True,
                default="pending",
                help_text="Current status of object.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scheduledpost",
            name="last_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When was the last failed attempt occur?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("error", "Error, awaiting retry."),
                    ("failed", "Failed to post after multiple retries. Giving up."),
                    ("queued", "Queued on remote server"),
                    ("complete", "Sucessfully posted."),
                ],
                db_index=True,
                default="pending",
                help_text="Current status of object.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scheduledthread",
            name="last_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When was the last failed attempt occur?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledthread",
            name="queued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If the remotes system supports queuing, what time did we successfully queue for?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledthread",
            name="remote_id",
            field=models.CharField(
                blank=True,
                help_text="Id of sent item on the remote system.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledthread",
            name="remote_queue_id",
            field=models.CharField(
                blank=True,
                help_text="What remote id did the target server give to the queued object?",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledthread",
            name="remote_url",
            field=models.URLField(
                blank=True,
                help_text="URL of sent item on the remote system.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="account",
            field=models.ForeignKey(
                help_text="Social account this is linked to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_boosts",
                to="post_later.account",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, help_text="When item was successfully sent.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="last_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When was the last failed attempt occur?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="next_retry",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="If failed, when is the next attempt to send.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="num_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of failed attempts to send."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="remote_id",
            field=models.CharField(
                blank=True,
                help_text="Id of sent item on the remote system.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="remote_url",
            field=models.URLField(
                blank=True,
                help_text="URL of sent item on the remote system.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledboost",
            name="send_at",
            field=models.DateTimeField(
                db_index=True, help_text="When to initiate sending to remote system."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, help_text="When item was successfully sent.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="next_retry",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="If failed, when is the next attempt to send.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="num_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of failed attempts to send."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="queued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If the remotes system supports queuing, what time did we successfully queue for?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="remote_id",
            field=models.CharField(
                blank=True,
                help_text="Id of sent item on the remote system.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="remote_queue_id",
            field=models.CharField(
                blank=True,
                help_text="What remote id did the target server give to the queued object?",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="remote_url",
            field=models.URLField(
                blank=True,
                help_text="URL of sent item on the remote system.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="send_at",
            field=models.DateTimeField(
                db_index=True, help_text="When to initiate sending to remote system."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledthread",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, help_text="When item was successfully sent.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheduledthread",
            name="next_publish",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="If started, when will the next post publish?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledthread",
            name="next_retry",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="If failed, when is the next attempt to send.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledthread",
            name="num_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of failed attempts to send."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledthread",
            name="send_at",
            field=models.DateTimeField(
                db_index=True, help_text="When to initiate sending to remote system."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledthread",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("error", "Error, awaiting retry."),
                    ("failed", "Failed to post after multiple retries. Giving up."),
                    ("queued", "Queued on remote server"),
                    ("complete", "Sucessfully posted."),
                ],
                db_index=True,
                default="pending",
                help_text="Current status of object.",
                max_length=20,
            ),
        ),
    ]
