# Generated by Django 4.1.3 on 2023-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0024_alter_account_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledboost",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this task is queued, sets a timestamp for default lock expiration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledpost",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this task is queued, sets a timestamp for default lock expiration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledthread",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this task is queued, sets a timestamp for default lock expiration.",
                null=True,
            ),
        ),
    ]
