# Generated by Django 4.1.3 on 2023-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_later", "0025_scheduledboost_locked_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="remote_queue",
            field=models.BooleanField(
                default=False, help_text="Does this account support remote queuing?"
            ),
        ),
    ]
